### ISSUE TITLE
Production use?

### ISSUE THREAD

**Issue by alexkahn** [yougov/yg-buildpack-python3#6]
Hey, wondering if this is WIP status or something you're using in production - been looking for something like this.

Thanks for making it public!

**Comment by jaraco** [comment]
We are using this in production for several apps, although we're deploying against [Velociraptor](https://bitbucket.org/yougov/velociraptor) and not Heroku proper.

**Comment by alexkahn** [comment]
Thanks for getting back to me so quickly, read through the velociraptor docs and really want to spin it up - looks awesome!

**Comment by jaraco** [comment]
Velociraptor is great, but also has some rough edges. Don't hesitate to reach out to us with tickets if you get stuck.
